// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: userProfile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO UserProfile (username, full_name, age, gender, height_cm, height_ft_in, preferred_unit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING user_profile_id, username, full_name, age, gender, height_cm, height_ft_in, preferred_unit, created_at
`

type CreateUserProfileParams struct {
	Username      string     `json:"username"`
	FullName      string     `json:"full_name"`
	Age           int32      `json:"age"`
	Gender        string     `json:"gender"`
	HeightCm      int32      `json:"height_cm"`
	HeightFtIn    string     `json:"height_ft_in"`
	PreferredUnit Weightunit `json:"preferred_unit"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (Userprofile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.Username,
		arg.FullName,
		arg.Age,
		arg.Gender,
		arg.HeightCm,
		arg.HeightFtIn,
		arg.PreferredUnit,
	)
	var i Userprofile
	err := row.Scan(
		&i.UserProfileID,
		&i.Username,
		&i.FullName,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.HeightFtIn,
		&i.PreferredUnit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserProfile = `-- name: DeleteUserProfile :exec
DELETE FROM UserProfile
WHERE username = $1
`

func (q *Queries) DeleteUserProfile(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUserProfile, username)
	return err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT userprofile.user_profile_id, userprofile.username, userprofile.full_name, userprofile.age, userprofile.gender, userprofile.height_cm, userprofile.height_ft_in, userprofile.preferred_unit, userprofile.created_at,users.username, users.email, users.password_hash, users.password_changed_at, users.created_at
FROM UserProfile
JOIN users ON UserProfile.username = users.username
WHERE UserProfile.username = $1 LIMIT 1
`

type GetUserProfileRow struct {
	Userprofile Userprofile `json:"userprofile"`
	User        User        `json:"user"`
}

func (q *Queries) GetUserProfile(ctx context.Context, username string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, username)
	var i GetUserProfileRow
	err := row.Scan(
		&i.Userprofile.UserProfileID,
		&i.Userprofile.Username,
		&i.Userprofile.FullName,
		&i.Userprofile.Age,
		&i.Userprofile.Gender,
		&i.Userprofile.HeightCm,
		&i.Userprofile.HeightFtIn,
		&i.Userprofile.PreferredUnit,
		&i.Userprofile.CreatedAt,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.PasswordChangedAt,
		&i.User.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE UserProfile
SET 
full_name = COALESCE($1,full_name),
age = COALESCE($2,age),
gender = COALESCE($3,gender), 
height_cm = COALESCE($4,height_cm),
height_ft_in = COALESCE($5,height_ft_in),
preferred_unit = COALESCE($6,preferred_unit)
WHERE username = $7
RETURNING user_profile_id, username, full_name, age, gender, height_cm, height_ft_in, preferred_unit, created_at
`

type UpdateUserProfileParams struct {
	FullName      pgtype.Text    `json:"full_name"`
	Age           pgtype.Int4    `json:"age"`
	Gender        pgtype.Text    `json:"gender"`
	HeightCm      pgtype.Int4    `json:"height_cm"`
	HeightFtIn    pgtype.Text    `json:"height_ft_in"`
	PreferredUnit NullWeightunit `json:"preferred_unit"`
	Username      string         `json:"username"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (Userprofile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FullName,
		arg.Age,
		arg.Gender,
		arg.HeightCm,
		arg.HeightFtIn,
		arg.PreferredUnit,
		arg.Username,
	)
	var i Userprofile
	err := row.Scan(
		&i.UserProfileID,
		&i.Username,
		&i.FullName,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.HeightFtIn,
		&i.PreferredUnit,
		&i.CreatedAt,
	)
	return i, err
}
